name: Build and Test Package

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkut Repository
        uses: actions/checkout@v2

      - name: Setup PureScript Tooling
        uses: purescript-contrib/setup-purescript@main

      - name: Cache PureScript dependencies
        uses: actions/cache@v2
        with:
          key: spago-${{ hashFiles('spago.lock') }}-${{ hashFiles('src/**/*.purs') }}
          path: |
            .spago
            output

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Build Package
        run: pnpm build

      - name: Test Package
        run: pnpm test
